export const LOGIN = "LOGIN";
export const UPDATE_INFOR = "UPDATE_INFOR";
export const UPDATE_INFOR_FAILED = "UPDATE_INFOR_FAILED";
export const UPDATE_INFOR_SUCCESS = "UPDATE_INFOR_SUCCESS";

export const WATCH_SAVE_USER_DATA = "WATCH_SAVE_USER_DATA";
export const WATCH_UPDATE_USER_DATA = "WATCH_UPDATE_USER_DATA";
export const GET_USER_INFO = "GET_USER_INFO";
export const UPDATE_NOTIFIFY_NUMBER = "UPDATE_NOTIFIFY_NUMBER";
export const SAVE_NOTIFICATION = "SAVE_NOTIFICATION";
export const SHOWLOADING = "SHOWLOADING";
export const HIDELOADING = "HIDELOADING";
