// const root = "http://123.25.24.165:8443/api";
const root = "https://apigw.dcvfinance.com/api";

export default {
  urlLogin: `${root}/auth/adminLogin`,
  urlLogout: `${root}/auth/adminLogout`,
  urlChangePass: `${root}/auth/adminChangePass`,
  urlUpdateUser: `${root}/auth/adminUpdateUserInfo`,
  urlDetailUser: `${root}/auth/adminGetUserInfo`,
  urlGetOTP: `${root}/auth/sendCodeForgetAdmin`,
  urlConfirmOTP: `${root}/auth/confirmCodeForgetAdmin`,
  urlConfirmPass: `${root}/auth/changePassForgetAdmin`,
  urlGetInfor: `${root}/auth/adminGetUserInfo`,

  urlGetListAction: `${root}/action/list`,
  urlCreateAction: `${root}/action/create`,
  urlUpdateAction: `${root}/action/update`,
  urlDeleteAction: `${root}/action/delete`,
  urlDetailAction: `${root}/action`,
  changeStatusAction: `${root}/action/changeStatus`,

  urlGetListBranch: `${root}/branch/list`,
  urlCreateBranch: `${root}/branch/create`,
  urlUpdateBranch: `${root}/branch/update`,
  urlDeleteBranch: `${root}/branch/delete`,
  urlDetailBranch: `${root}/branch`,
  urlListEmployeeBranch: `${root}/branch/listBranchEmployee`,
  changeStatusBranch: `${root}/branch/changeStatus`,

  urlGetListGroup: `${root}/usergroup/list`,
  urlCreateGroup: `${root}/usergroup/create`,
  urlUpdateGroup: `${root}/usergroup/update`,
  urlDeleteGroup: `${root}/usergroup/delete`,
  urlDetailGroup: `${root}/usergroup`,
  urlListActionByGroup: `${root}/usergroup/permission`,
  changeStatusGroup: `${root}/usergroup/changeStatus`,

  urlGetListNotification: `${root}/notification/list`,
  urlCreateNotification: `${root}/notification/create`,
  urlUpdateNotification: `${root}/notification/update`,
  urlDeleteNotification: `${root}/notification/delete`,
  urlDetailNotification: `${root}/notification`,
  urlgetListObjectType: `${root}/dropdown/objecttype`,
  urlgetListNotifcationType: `${root}/dropdown/notificationtype`,
  urlgetListModuleDropdown: `${root}/dropdown/module`,
  changeStatusNotification: `${root}/notification/changeStatus`,

  urlGetListNotificationType: `${root}/notificationtype`,
  urlCreateNotificationType: `${root}/notificationtype/create`,
  urlUpdateNotificationType: `${root}/notificationtype/update`,
  urlDeleteNotificationType: `${root}/notificationtype/delete`,
  urlNotificationType: `${root}/notificationtype/list`,
  changeStatusTypeNotification: `${root}/notificationtype/changeStatus`,

  urlGetListEvent: `${root}/event`,
  detailEvent: `${root}/event`,
  urlCreateEvent: `${root}/event/create`,
  urlUpdateEvent: `${root}/event/update`,
  urlDeleteEvent: `${root}/event/delete`,
  urlEvent: `${root}/event/list`,
  changeStatusEvent: `${root}/event/changeStatus`,
  urlDropModule: `${root}/dropdown/module`,
  urlDropEventType: `${root}/dropdown/eventtype`,
  dropDownModuleType: `${root}/dropdown/moduletype`,

  urlGetListModule: `${root}/module`,
  urlCreateModule: `${root}/module/create`,
  urlUpdateModule: `${root}/module/update`,
  urlDeleteModule: `${root}/module/delete`,
  urlModule: `${root}/module/list`,
  changeStatusModule: `${root}/module/changeStatus`,

  urlGetListModuleType: `${root}/moduletype`,
  urlCreateModuleType: `${root}/moduletype/create`,
  urlUpdateModuleType: `${root}/moduletype/update`,
  urlDeleteModuleType: `${root}/moduletype/delete`,
  urlModuleType: `${root}/moduletype/list`,
  changeStautsModuleType: `${root}/moduletype/changeStatus`,

  urlGetListBanner: `${root}/banner`,
  urlCreateBanner: `${root}/banner/create`,
  urlUpdateBanner: `${root}/banner/update`,
  urlDeleteBanner: `${root}/banner/delete`,
  urlBanner: `${root}/banner/list`,
  changeStatusBanner: `${root}/banner/changeStatus`,

  urlGetListConfig: `${root}/settings/list`,
  urlCreateConfig: `${root}/settings/create`,
  urlUpdateConfig: `${root}/settings/update`,
  urlDeleteConfig: `${root}/settings/delete`,
  urlDetailConfig: `${root}/settings`,
  changeStatusConfig: `${root}/settings/changeStatus`,

  urlGetListStaticpage: `${root}/staticpage/list`,
  urlCreateStaticpage: `${root}/staticpage/create`,
  urlUpdateStaticpage: `${root}/staticpage/update`,
  urlDeleteStaticpage: `${root}/staticpage/delete`,
  urlDetailStaticpage: `${root}/staticpage`,
  changeStatusStaticPage: `${root}/staticpage/changeStatus`,

  urlGetListMethod: `${root}/function/list`,
  urlCreateMethod: `${root}/function/create`,
  urlUpdateMethod: `${root}/function/update`,
  urlDeleteMethod: `${root}/function/delete`,
  urlDetailMethod: `${root}/function`,
  urlListMethodPicker: `${root}/function/lstFunctionPermission`,
  changeStatusMethod: `${root}/function/changeStatus`,

  urlGetListLogin: `${root}/logging/listLogin`,
  urlGetListApi: `${root}/logging/listCallApi`,
  urlGetListLoginAction: `${root}/logging/listAction`,

  urlUploadFile: `${root}/upload/uploadfile`,

  urlGetListEmployee: `${root}/user/list`,
  urlCreateEmployee: `${root}/user/create`,
  urlUpdateEmployee: `${root}/user/update`,
  urlDeleteEmployee: `${root}/user/delete`,
  urlDetailEmployee: `${root}/user`,
  changeStatusEmployee: `${root}/user/changeStatus`,

  urlDropdownGroup: `${root}/dropdown/usergroup`,
  urlDropdownEvent: `${root}/dropdown/event`,
  urlDropdownInvestType: `${root}/dropdown/investorType`,
  urlDropdownInvestAction: `${root}/dropdown/investorActionByType`,
  urlDropdownStatusCard: `${root}/dropdown/cardStatus`,
  urlDropdownBranch: `${root}/dropdown/branch`,
  urlDropdownStatusTrans: `${root}/dropdown/cusTransStatus`,
  dropdownConfigTypePoint: `${root}/dropdown/pointConfigType`,
  dropdownReqStatus: `${root}/dropdown/reqStatus`,
  dropdownTransStatus: `${root}/dropdown/transStatus`,
  dropdownListPackage: `${root}/dropdown/investmentPackage`,
  dropdownContractType: `${root}/dropdown/contractType`,
  dropdwonSourceCard: `${root}/dropdown/sourceCreditCard`,
  dropdwonfuntions: `${root}/dropdown/function`,
  dropdwonEvent: `${root}/dropdown/event`,
  dropDwonActionAgent: `${root}/dropdown/transAction`,
  dropDwonApproveStatus: `${root}/dropdown/approveStatus`,
  dropDownUserApprove: `${root}/dropdown/userApprove`,
  dropDownBank: `${root}/dropdown/bank`,

  //home
  adminCommon: `${root}/dashboard/adminCommon`,
  dashboardTable: `${root}/dashboard/adminInvestPackage`,
  adminAnalyst: `${root}/dashboard/adminAnalyst`,

  //VA
  epaytrans: `${root}/epaytrans/list`,
};
